apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: edge-runner-staged
on:
  workflow_dispatch:
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
jobs:
  job1:
    runs-on:
      - my-label-1
      - my-label-2
      - os:darwin
      - arch:arm64
      - self-hosted
      - default
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
